name: CI

on:
  push:
    branches:
      - feature-github_actions
  pull_request:
    branches:
      - feature-github_actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - run: |
          pip install Flask
          pip install requests
          pip install python-dotenv

      # Run the tests
      #- run: |
      #     python -m unittest

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PWD }}

      - run: |
          docker build . -t python:nasa_api
          docker tag python:nasa_api python:nasa_api
          docker push gregoiremathian/ci-cd_project:tag_name